name: Compilar proyecto

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet build PracticaCI
      - run: dotnet test PracticaCI.Tests/PracticaCI.Tests.csproj

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir y subir imagen
        uses: docker/build-push-action@v6
        with:
          context: ./PracticaCI
          push: true
          tags: octta/practica-ci:latest
